name: TeleportBetweenBedsPlugin
version: ALPHA-0.1.3
api-version: '1.19'
main: org.batzi1337.teleportbetweenbeds.TeleportBetweenBeds
author: Marco & Marco
description: A Bukkit plugin that allows players to teleport between beds.
commands:
  tpbed:
    description: Teleports the player to the closest bed.
    usage: /tpbed
permissions:
  tpbed.*:
    description: Gives access to all tpbed commands.
    children:
      tpbed.use: true
      tpbed.admin: true
  tpbed.use:
    default: true
    description: Allows you to use /tpbed.
  tpbed.admin:
    default: op
    description: Allows you to use additional commands.